KU-1
tungatarovKl/ku1-newsletter-admin pull request #1
Opened 2022-11-10 07:45 UTC by KornilovVl

Установил Laravel
Добавил роут для /newsletter
Добавил дефолтный шаблон и шаблон для отображения страницы /newsletter
Подключил Bootstrap в дефолтный шаблон
Написал краткий гайд по использованию шаблонов
Подключил создал пустую БД и подключил sqlite
Написал Readme как поднять проект

2022-11-10 11:30 UTC, tungatarovKl requested changes
убираем стандартные комменты laravel во всех файлах.

2022-11-10 11:30 UTC, tungatarovKl commented on .env
> +APP_NAME=ku1-newsletter-admin
этот файл нужно добавить .gitignore. Оно у каждого личная и копируется из .env.example при локальном поднятий проекта

2022-11-10 11:30 UTC, tungatarovKl commented on .env
> +APP_NAME=ku1-newsletter-admin
Все изменения нужно хранить в .env.example. Т.е нужно все перенести в .env.example

2022-11-10 11:30 UTC, tungatarovKl commented on README.md
> +2. Прописать абсолютный путь до базы данных
нужно добавить инструкцию как инициализировать бд в sqlite

2022-11-10 11:30 UTC, tungatarovKl commented on README.md
> +nano .env
нужно указать что нужно создать новый файл .env у себя и скопировать туда содержимое файла .env.example

2022-11-10 11:30 UTC, tungatarovKl commented on app/Console/Kernel.php
> +        // $schedule->command('inspire')->hourly();
убрать дебаг, оставить пустой метод

2022-11-10 11:30 UTC, tungatarovKl commented on app/Exceptions/Handler.php
> +    protected $levels = [
нужно убрать не нужное поле

2022-11-10 11:30 UTC, tungatarovKl commented on app/Exceptions/Handler.php
> +     */
тоже убираем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Exceptions/Handler.php
> +            //
можно оставить пустой метод

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Kernel.php
> +        \App\Http\Middleware\TrustProxies::class,
оставляем пустой массив

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Kernel.php
> +    protected $middlewareGroups = [
пока оставляем пустой массив с пустыми api, web

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Kernel.php
> +    protected $routeMiddleware = [
пока оставляем пустой массив

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/Authenticate.php
> +<?php
пока удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/EncryptCookies.php
> +<?php
пока удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/PreventRequestsDuringMaintenance.php
> +<?php
пока удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/TrimStrings.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/TrustHosts.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/TrustProxies.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/ValidateSignature.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Http/Middleware/VerifyCsrfToken.php
> +
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Providers/AuthServiceProvider.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on app/Providers/BroadcastServiceProvider.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on artisan
> +/*
убираем стандартные комиты от ларавел

2022-11-10 11:30 UTC, tungatarovKl commented on bootstrap/app.php
> +<?php
тут тоже убираем комменты от ларавел

2022-11-10 11:30 UTC, tungatarovKl commented on config/app.php
> +        Illuminate\Auth\AuthServiceProvider::class,
убираем все провайдеры начинающийся с Illuminate

2022-11-10 11:30 UTC, tungatarovKl commented on config/app.php
> +        // App\Providers\BroadcastServiceProvider::class,
убираем auth, broadcast

2022-11-10 11:30 UTC, tungatarovKl commented on config/app.php
> +    /*
убираем стандартные комменты ларавел

2022-11-10 11:30 UTC, tungatarovKl commented on config/app.php
> +        // 'ExampleClass' => App\Example\ExampleClass::class,
убираем закомменченный код

2022-11-10 11:30 UTC, tungatarovKl commented on config/auth.php
> +
убираем стандартные комменты ларавел

2022-11-10 11:30 UTC, tungatarovKl commented on config/auth.php
> +        // 'users' => [
убираем закоменченный код

2022-11-10 11:30 UTC, tungatarovKl commented on config/broadcasting.php
> +        'pusher' => [
убираем pusher, ably, redis

2022-11-10 11:30 UTC, tungatarovKl commented on config/cache.php
> +return [
убираем стандартные комменты ларавел

2022-11-10 11:30 UTC, tungatarovKl commented on config/cache.php
> +
убираем apc, array, memcached, redis, dynamodb, database. Оставляем только файл

2022-11-10 11:30 UTC, tungatarovKl commented on config/database.php
> +        'mysql' => [
убрать пока mysql, postgres, sqlsrv

2022-11-10 11:30 UTC, tungatarovKl commented on config/database.php
> +
убрать redis полностью

2022-11-10 11:30 UTC, tungatarovKl commented on config/filesystems.php
> +        'local' => [
убрать s3

2022-11-10 11:30 UTC, tungatarovKl commented on config/logging.php
> +    'channels' => [
оставить только stderr

2022-11-10 11:30 UTC, tungatarovKl commented on config/mail.php
> +<?php
удаляем  файл

2022-11-10 11:30 UTC, tungatarovKl commented on config/queue.php
> +    'connections' => [
убираем, database, beanstalk, sqs, redis

2022-11-10 11:30 UTC, tungatarovKl commented on config/sanctum.php
> +<?php
удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on config/services.php
> +<?php
удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +<?php
удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on lang/en/pagination.php
> +<?php
удаляем файл

2022-11-10 11:30 UTC, tungatarovKl commented on lang/en/passwords.php
> +<?php
папку lang полностью удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on phpunit.xml
> +<?xml version="1.0" encoding="UTF-8"?>
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on public/.htaccess
> +<IfModule mod_rewrite.c>
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on public/robots.txt
> +User-agent: *
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on resources/js/bootstrap.js
> +window._ = _;
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on resources/views/README.md
> +# Templates development guide
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on routes/api.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on routes/channels.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on routes/console.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on tests/CreatesApplication.php
> +<?php
пока удаляем

2022-11-10 11:30 UTC, tungatarovKl commented on tests/CreatesApplication.php
> +<?php
давай лучше папку tests полностью удалим

2022-11-10 11:30 UTC, tungatarovKl commented on vite.config.js
> +import { defineConfig } from 'vite';
пока удаляем

2022-11-11 04:31 UTC, tungatarovKl requested changes
не все файлы удалены, плюс нужно очистить массивы миддлаваров

2022-11-11 04:31 UTC, tungatarovKl commented on README.md
> +4. Сгенерировать APP-KEY в файле .env
опиши плз как генерит app-key

2022-11-11 04:48 UTC, tungatarovKl requested changes
не все файлы удалены + не все ревью исправлены)

2022-11-11 04:48 UTC, tungatarovKl commented on config/app.php
> +    /*
убираем комменты от ларавел

2022-11-11 04:48 UTC, tungatarovKl commented on config/hashing.php
> +    /*
стандартные коммиты ларавела

2022-11-11 04:48 UTC, tungatarovKl commented on config/logging.php
> +    |--------------------------------------------------------------------------
тут тоже коммиты ларавел

2022-11-11 04:48 UTC, tungatarovKl commented on config/session.php
> +return [
стандартные комменты ларавел

2022-11-11 04:48 UTC, tungatarovKl commented on config/view.php
> +    /*
стандартные комменты ларавел

2022-11-11 15:27 UTC, KornilovVl commented on resources/views/README.md
> +# Templates development guide
Так это же мое рукотворное ридми :D

2022-11-11 17:46 UTC, KornilovVl commented
Прошелся еще раз по комментам, довыпиливал все что возможно из указанного.
Дополнил ридми генерацией ключа, избавился от главной демо-страницы (сделал роутинг с / на /newsletter)

2022-11-12 13:42 UTC, closed without merging