Добавляю token в POST- запрос, улучшаю обработку ошибок, небольшой рефакторинг. Добавил сеть в настройки докера, изменил названия сервисов и хостнеймы контейнеров
tungatarovKl/ku1-newsletter-admin pull request #4
Opened 2022-11-14 20:13 UTC by KornilovVl

…а сервиса

Русифицировал шаблон newsletter.blade.php, удалил нерабочие кнопки Добавил обработку ошибок при отправке POST- request на сервис Сделал небольшой рефакторинг- переименовал переменные, классы и роуты для лучшего отображения функционала

Обновил docker-compose.yml:
Изменил названия сервисов и хостнеймы
Добавил параметры сети
Протестировал работу в связке с messenger
Написал unit-test на роут /sendMessage

2022-11-14 20:15 UTC, KornilovVl commented
![](https://github.trello.services/images/mini-trello-icon.png) [KU-7 Добавить токен при отправке запроса на микросервис рассылки](https://trello.com/c/hBRpVv31/9-ku-7-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD-%D0%BF%D1%80%D0%B8-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B5-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%BD%D0%B0-%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81-%D1%80%D0%B0%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8)

2022-11-15 05:03 UTC, tungatarovKl approved these changes

2022-11-15 05:03 UTC, tungatarovKl commented on app/Http/Controllers/SendMessageController.php
> +            return redirect('/newsletter')->with('error','Ошибка соединения с сервером');
тут бы полагировать, а то в случае ошибок не понятно будет

2022-11-16 03:27 UTC, tungatarovKl requested changes

2022-11-16 03:27 UTC, tungatarovKl commented on app/Http/Controllers/SendMessageController.php
>              return redirect('/newsletter')->with('error','Ошибка соединения с сервером');
строка между Log и return

2022-11-16 03:27 UTC, tungatarovKl commented on app/Http/Controllers/SendMessageController.php
> +            Log::channel('stderr')->error($e->getMessage());
можно сделать текст ошибки статическим а сообщение ошибки передать в теле лога. Да, у тебя будут логи в случае ошибок, но когда логов будет несколько сотен из разных мест. Станет непонятно, где происходит ошибка. А имея статический текст, мы по проекту можем быстро найти где именно происходит ошибка
Log::channel('stderr')->error('<какой-то текст>', ['message' => $e->getMessage()]);

2022-11-16 03:27 UTC, tungatarovKl commented on app/Http/Controllers/SendMessageController.php
>          return redirect('/newsletter')->with('error','Ошибка отправки сообщения');
строка между log и return

2022-11-16 03:27 UTC, tungatarovKl commented on app/Http/Controllers/SendMessageController.php
> +        Log::channel('stderr')->error([
также статический текст нужен для лога. Подробнее в другом комменте

2022-11-17 09:12 UTC, tungatarovKl approved these changes

2022-11-17 12:39 UTC, wildb-ee approved these changes
Согласен со всеми изменениями,

2022-11-17 14:59 UTC, merged